### ISSUE TITLE
Cancel audio output when leaving screen

### ISSUE THREAD

**Issue by noerw** [ShacharHarshuv/open-ear#120]
Thanks for the great app!

I noticed that played audio (notes as well as songs from the 'chord progressions in real songs' feature) keep playing, when i exit the exercise. This can be quite annoying.

**Comment by ShacharHarshuv** [comment]
Hey, I think this is resolved with this PR: https://github.com/ShacharHarshuv/open-ear/pull/102, so the fix should be available in the next release. 
However, even after this fix the last note played will sustain until it's over. I couldn't find a way to fix that yet. Songs from youtube will stop immediately.
