### ISSUE TITLE
UX problems in exercises

### ISSUE THREAD

**Issue by noerw** [ShacharHarshuv/open-ear#121]
When answering there are a few UX challenges, often leading me to wrong inputs (± 1 in 8 exercises):

- Pressing a button is not registered when swiping slightly before letting go (instead of registering on touch-start).
- Feedback of a incorrect answer is minimal (the `?` turns red), and easily missed.

The combination of these led me to think that my input was wrong, whereas it just wasn't registered.

**Comment by ShacharHarshuv** [comment]
> Pressing a button is not registered when swiping slightly before letting go (instead of registering on touch-start).

I believe this is the common behavior for buttons in most apps (the event is on release, not touch-start). I actually I couldn't find any app I know that registers clicks on touch-release. 

> Feedback of a incorrect answer is minimal (the ? turns red), and easily missed.

The button you clicked on will turn red as well. Is this not enough?

**Comment by noerw** [comment]
> I believe this is the common behavior for buttons in most apps (the event is on release, not touch-start). I actually I couldn't find any app I know that registers clicks on touch-release.

That's true. I primarily outlined this to illustrate the problem, not expecting a change in behaviour

> The button you clicked on will turn red as well. Is this not enough?

It doesn't for me (I'm on the latest fdroid version 1.2.6)

**Comment by ShacharHarshuv** [comment]
> That's true. I primarily outlined this to illustrate the problem, not expecting a change in behaviour

If that's the case it's unclear to me if you're expecting any improvement and if so what should it be.

> It doesn't for me (I'm on the latest fdroid version 1.2.6)

This version is out of date. I'm not maintaining the f-droid builds, maybe @proletarius101 can help.
Otherwise you can download the latest version from google play.

**Comment by noerw** [comment]
>> That's true. I primarily outlined this to illustrate the problem, not expecting a change in behaviour
>
> If that's the case it's unclear to me if you're expecting any improvement and if so what should it be.

I was talking about changing the button behavior only. A more prominent wrong-answer highlighting would still be helpful to avoid this issue.

> This version is out of date.

Ah, I didn't check. Great if that's already improved :+1:
