### ISSUE TITLE
Credits Link is broken

### ISSUE THREAD

**Issue by themrvideouser** [ShacharHarshuv/open-ear#146]
Credits
Piano samples used by Jan Frost from [@audio-samples/piano-mp3-*](https://github.com/darosh/samples-piano-mp3%5D).
The link has a trailing closing bracket "]" which breaks it.
Without it, it works: https://github.com/darosh/samples-piano-mp3

**Comment by ShacharHarshuv** [comment]
Fixed: https://github.com/ShacharHarshuv/open-ear/pull/147
