### ISSUE TITLE
The following enhancements can be made to further improve this app

### ISSUE THREAD

**Issue by lkoinng** [ShacharHarshuv/open-ear#195]
Below are some of the improvements that can be made in my opinion, ranked by importance and necessity:

1. Allow users to change keys freely
> when I play the exercises (mainly chord functions), i cannot change the key nor will it change by itself (even when i switched to different exercises). If i have to practise listening to different keys, i will have to manually shut down the app and re-open it

2. Increase the volume
> the volume of music in the exercises is generally low. I have a hard time listening to the exercises when i am in public area if i dont turn the volume up to 70-80% (even with headphones)

3. Allow the same chord to be played consecutively in a single run 
> currently in chord functions exercise (i dont know about the others), the same chord wont be played consecutively (e.g. I -> I -> V -> V isn’t allowed). Yet i think this is also a great way to train ears 

4. Allow individual chords to be played back when repeating
> in chord functions exercise, when i want to repeat one of the chords played, it repeats all chords. but sometimes i just wanted to listen back to one chord only

5. Add new instruments 
> since in real songs, piano isn’t the only instrument. New instruments such as guitars or winds may be added to enhance the ear training result. You may also consider allowing multiple instruments to be played at the same time in the exercises

All in all, it is a great app and it does improve my relative pitch 
great job developers :)

**Comment by ShacharHarshuv** [comment]
Hey, please open a separate ticket for each issue. For some reason I missed this ticket so I'm replying in a delay of over a year.

---

> Allow users to change keys freely

I think what you are looking for was implemented [here](https://github.com/ShacharHarshuv/open-ear/pull/170)

> Increase the volume

I'm using the third party samples as is. I believe it's using the same sample for every velocity and I might not be using the maximum velocity, so it's possible it's not playing in maximum volume. Anyway please open a separate ticket. 

> Allow the same chord to be played consecutively in a single run

I guess that could be a setting. Please create a separate ticket. 

> Allow individual chords to be played back when repeating

I think having to listen to everything is part of the exercise, as context really matters. If you want to practice identifying individual chords, you can select one chord in the exercise settings.
