### ISSUE TITLE
modes to identify drum patterns, time signatures, hertz values, notes, scale / mode of scale

### ISSUE THREAD

**Issue by RustoMCSpit** [ShacharHarshuv/open-ear#226]
would also be cool if there was a hybrid mode that meant you had to idenify the drums, melody and chords at the same time

**Comment by ShacharHarshuv** [comment]
@RustoMCSpit Hey, I'm not sure if all that you described here is in the scope of the app's purpose (which is currently focused on tonal identification)

If you seriously want to suggest these new features, please create a dedicated issue for every feature with more details explaining what your suggestion. 

Closing for now.
