### ISSUE TITLE
mode to identify bpm

### ISSUE THREAD

**Issue by RustoMCSpit** [ShacharHarshuv/open-ear#230]
have a beat play for 5 seconds and have the user input the bpm, easy mode is jusr whole beats but harder modes have more rypes of note

**Comment by ShacharHarshuv** [comment]
Why is that a useful skill for a musician to identify bpms?

**Comment by RustoMCSpit** [comment]
> Why is that a useful skill for a musician to identify bpms?

basic ear training that complements everything else, helps you stay in time too

**Comment by ShacharHarshuv** [comment]
> basic ear training that complements everything else, helps you stay in time too

I've never heard that in any educational source. Can you please reference one? Where did you hear that it's basic ear training and it helps you stay in time?

**Comment by RustoMCSpit** [comment]
> > basic ear training that complements everything else, helps you stay in time too
> 
> I've never heard that in any educational source. Can you please reference one? Where did you hear that it's basic ear training and it helps you stay in time?

well it's like a metronome, training yourself to hear the pulse of a song while in a band will help you stay in time and rhats what this practices

**Comment by ShacharHarshuv** [comment]
This seems like a instrument practice thing, not a ear training thing, so I don't think it fits the app. I have heard no source or recommended to learn to identify bpms. (Just pull out your phone and tap if you need it, or feel the beat and play). I'm closing this suggestion for now.
