### ISSUE TITLE
mode to identify hertz values

### ISSUE THREAD

**Issue by RustoMCSpit** [ShacharHarshuv/open-ear#232]
a sin wave will play, your job is to input what hertz value it's playing at. harder modes will include microtonal values while easier modes will stick to 12 tet. this is a harder version of note based detection as you also have to get the specific octave right

**Comment by ShacharHarshuv** [comment]
Why is that a useful technique for a musician to have? 

Most of us are not born with perfect pitch and you don't need perfect pitch in order to understand music. 

From my experience I believe it's best to stay away from exercises like these.

**Comment by RustoMCSpit** [comment]
> Why is that a useful technique for a musician to have?
> 
> Most of us are not born with perfect pitch and you don't need perfect pitch in order to understand music.
> 
> From my experience I believe it's best to stay away from exercises like these.

it helps with relative pitch as well? most of us have that

**Comment by ShacharHarshuv** [comment]
> it helps with relative pitch as well? 

This is incorrect, training with absolute values actually hurt your relative pitch as it comes in contradiction to the natural way our brain processes music and can only be confusing. I'm closing this ticket and recommend you to stay away from this kind of exercise, even if you DO have perfect pitch.
