### ISSUE TITLE
mode to identify notes

### ISSUE THREAD

**Issue by RustoMCSpit** [ShacharHarshuv/open-ear#233]
a note will play, guess it. harder mode will include octaves and 12 notes rather than just a scale

**Comment by ShacharHarshuv** [comment]
You mean absolute note detection? This is a very inefficient way to train your ear as most of us are not born with perfect pitch, and even if you are born with perfect pitch, thinking of music as absolute pitches distorts your perception of how music works. (I have perfect-pitch friends and they struggle with it)

**Comment by RustoMCSpit** [comment]
> You mean absolute note detection? This is a very inefficient way to train your ear as most of us are not born with perfect pitch, and even if you are born with perfect pitch, thinking of music as absolute pitches distorts your perception of how music works. (I have perfect-pitch friends and they struggle with it)

it would be relative as youll be hearing other notes beforehand amd beimg told what they are in the easier  modes

**Comment by ShacharHarshuv** [comment]
Even if it's relative it would be atonal, and thus very confusing and counter intuitive. 

If you still want to do this kind of exercise, you can do that today with the regular note identification - just turn on all notes and set the scale to C major. This way 1 = C, 1# = C# tc.
