### ISSUE TITLE
Dialog box remains

### ISSUE THREAD

**Issue by EleanorToms** [ShacharHarshuv/open-ear#237]
I was using the Chord Functions setting, with the settings set to automatically move to the next question after a correct answer. I clicked back to change what feature of the app I was using, whilst the dialog box was still up to say "Playing cadence to establish key...". Then the dialog box remained, even when I started to use another feature. Until the app reloaded, when I went off it and back on again after a few minutes.

**Comment by ShacharHarshuv** [comment]
I think I've seen it but I don't have proper reproduction steps. Do you have a way to consistently reproduce it? 

Anyway, it will probably not get prioritized too much.

**Comment by EleanorToms** [comment]
Hello,

I have been able to reproduce the issue for all of the practice modes which
play a cadence to identify the key. So it applies to the following 5/8
practice modes: Scale Degrees; Chord Functions; Common Progressions; Chord
Progressions in Real Songs; Notes with Chords.

1. Click on the practice mode.
2. Whilst the "Playing cadence to establish key..." dialog box is open,
press the back arrow, to go back to select a new practice mode. This can be
either whilst the cadence is playing, or before it has started playing.

Result: the dialog box remains, both on the practice mode selection page,
and when I select a new practice mode. So it is a problem because it blocks
the options in the new practice mode.

I can only remove it by closing the app in my 'open apps' section and
restarting it.

I am using a Samsung Galaxy S9 phone, and I am using the beta version of
the app, version 1.6.0.

**Comment by EleanorToms** [comment]
I do have some basic programming knowledge. However I don't think I am
familiar enough with GitHub to use it. And I have only worked in Python so
far. I don't know that I would be able to spend the time on doing this work
for now, but I will bear it in mind for the future if I am able to take the
time.

**Comment by ShacharHarshuv** [comment]
Working with Github is usually the easy part, so don't let it discourage you. A basic tutorial on how to commit, push and open PRs will get you up to speed. (You don't need to be familiar with advanced features)

JavaScript is not that much different from python. I believe some basic tutorials in javascript, typescript (which is an extension of javascript) and Angular will ge tyou up to speed enough so you can work yourself around the existing code. 

Don't worry to make mistakes, as I'll review your code and will give you feedback before it's merge. 

Looking forward to getting a pull request if you get the time!

**Comment by EleanorToms** [comment]
Ok, thank you for the advice - I find it can be hard to know where to start
learning with these things, and what the extent of knowledge required is. I
feel more confident now that I might be able to help, if I can make time.

Thanks,
Eleanor.

**Comment by ShacharHarshuv** [comment]
Fixed in https://github.com/ShacharHarshuv/open-ear/pull/241
