### ISSUE TITLE
Analyse with notation shown

### ISSUE THREAD

**Issue by jtagcat** [ShacharHarshuv/open-ear#248]
Adding to #247 

Also show sheet music / notation.

**Comment by ShacharHarshuv** [comment]
Please add more details as to what you mean by this.

**Comment by entomologe** [comment]
I'm not exactly sure what the request is about but one part of it might be the request to include the option of musical notation. Would it be feasible to compile musical notations via lilypond or latex on the fly?

**Comment by ShacharHarshuv** [comment]
> I assume @ShacharHarshuv might answer this particular request similar to https://github.com/ShacharHarshuv/open-ear/issues/229#issuecomment-1753975293 ?

Yes. This app is focused on ear training in a way that is independent from notation. The assumption being that if you can identify the notes being played, and you know how to play them on your instrument, you can play from earing. Additionally, if you are familiar with music notation, you can use the same skill to notate from listening.

I'm closing this issue for now.
