### ISSUE TITLE
Idea: add tonic drone for tonal exercises

### ISSUE THREAD

**Issue by ShacharHarshuv** [ShacharHarshuv/open-ear#33]
This can help beginners feel the tension of each note / chord.
It should be possible to turn it on/off in the settings

**Comment by entomologe** [comment]
This is a good idea. The feature seems to be already included in "Scale Degrees"? 

Regarding setting on/off there is still the issue of https://github.com/ShacharHarshuv/open-ear/issues/201 : (

**Comment by ShacharHarshuv** [comment]
Yes seems like it was implemented already. Closing.
