### ISSUE TITLE
Triad inversion answer filtering is not working

### ISSUE THREAD

**Issue by ShacharHarshuv** [ShacharHarshuv/open-ear#55]
It's asking for answers that doesn't exist even if you deselect them.

**Comment by ItayHarshuv** [comment]
Fixed

**Comment by ShacharHarshuv** [comment]
https://github.com/ShacharHarshuv/open-ear/pull/61

For next time,  if you reference the task id in the branch / pull request name, GitHub will automatically link the issue to the Pr.
